### PR TITLE
Auto updated assets for terraform

### PR DESCRIPTION
**Pull request by yograjshisode**

### CODE REVIEW

**Comment by yograjshisode** [comment]
run jenkins-terraform-test

**Comment by ArpitAVI** [comment]
run jenkins-terraform-test

**Comment by ArpitAVI** [comment]
Commented trigger phase... because accidentally I had aborted the downstream test job for this one.

**Comment by ArpitAVI** [comment]
aborted terraform test since the listener job was blocking smoke build pipeline build nodes... Will create nodes for listener jobs and re-trigger the tests via phrase in a while

**Comment by yograjshisode** [comment]
run jenkins-terraform-test

**Comment by ArpitAVI** [comment]
run jenkins-terraform-test

**Comment by ArpitAVI** [comment]
run jenkins-terraform-test

**Comment by ArpitAVI** [comment]
run jenkins-terraform-test

**Comment by gurunath-avi** [comment]
run jenkins-terraform-test

**Comment by yograjshisode** [comment]
run jenkins-terraform-test

**Review by mayank-avinetworks — APPROVED** [review]

**Pull request merged**
