### PR TITLE
AV-112569 Update 18.2.13 for terraform registry and new terraform plugin

### PR DESCRIPTION
**Pull request by yograjshisode**

### CODE REVIEW

**Review by manojkumarjain — APPROVED** [review]
Approve

**Comment by ArpitAVI** [comment]
run jenkins-terraform-test

**Comment by ArpitAVI** [comment]
run jenkins-terraform-test

**Comment by ArpitAVI** [comment]
run jenkins-terraform-test

**Comment by ArpitAVI** [comment]
run jenkins-terraform-test

**Comment by chugh007** [comment]
run jenkins-terraform-test

**Comment by chugh007** [comment]
run jenkins-terraform-test

**Comment by gurunath-avi** [comment]
Terraform Test PASSED
 No test results found.

**Comment by chugh007** [comment]
run jenkins-terraform-test

**Comment by gurunath-avi** [comment]
Terraform Test PASSED
 No test results found.

**Comment by ArpitAVI** [comment]
run jenkins-terraform-test

**Comment by gurunath-avi** [comment]
Terraform Test FAILED
 No test results found.

**Comment by mayank-avinetworks** [comment]
Test

**Comment by ArpitAVI** [comment]
run jenkins-terraform-test

**Pull request merged**
