### PR TITLE
Auto updated assets for terraform

### PR DESCRIPTION
**Pull request by yograjshisode**

### CODE REVIEW

**Comment by ArpitAVI** [comment]
run jenkins-terraform-test

**Comment by yograjshisode** [comment]
run jenkins-terraform-test

**Comment by gurunath-avi** [comment]
run jenkins-terraform-test

**Comment by ArpitAVI** [comment]
run jenkins-terraform-test

**Comment by ArpitAVI** [comment]
run jenkins-terraform-test

**Pull request closed without merging**
